In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# prediction 1D
## prediction

In [2]:
w = torch.tensor(2.0, requires_grad = True )
b = torch.tensor(-1.0, requires_grad = True )
print (w,b)

tensor(2., requires_grad=True) tensor(-1., requires_grad=True)


In [3]:
def forward(x):
    yhat = w*x +b
    return yhat

In [4]:
x = torch.tensor([1.0])
yhat = forward(x)
print (yhat)

tensor([1.], grad_fn=<AddBackward0>)


In [5]:
x = torch.tensor([[1.0],[2.0]])
print (x)
print (x.shape)

tensor([[1.],
        [2.]])
torch.Size([2, 1])


In [6]:
yhat = forward(x)
print (yhat)
print (yhat.shape)

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)
torch.Size([2, 1])


## class linear

In [7]:
from torch.nn import Linear

In [8]:
lr = Linear(in_features=1, out_features=1, bias=True)
print (list(lr.parameters()))
print (type(lr))

[Parameter containing:
tensor([[0.8693]], requires_grad=True), Parameter containing:
tensor([-0.4289], requires_grad=True)]
<class 'torch.nn.modules.linear.Linear'>


**in_features** – size of each input sample

**out_features** – size of each output sample

**bias** – If set to False, the layer will not learn an additive bias. Default: True

In [9]:
print("Python dictionary: ",lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict([('weight', tensor([[0.8693]])), ('bias', tensor([-0.4289]))])
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[0.8693]]), tensor([-0.4289])])


In [10]:
print("weight:",lr.weight)
print("bias:",lr.bias)

weight: Parameter containing:
tensor([[0.8693]], requires_grad=True)
bias: Parameter containing:
tensor([-0.4289], requires_grad=True)


In [11]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print (yhat)

tensor([[0.4404]], grad_fn=<AddmmBackward>)


$ y = xW^{T} + b $

In [13]:
x = torch.tensor([[1.0],[2.0]])
yhat = lr(x)
print (yhat)

tensor([[0.4404],
        [1.3097]], grad_fn=<AddmmBackward>)


## build custom Modules

In [16]:
from torch import nn

In [17]:
class LR (nn.Module):
    def __init__ (self, input_size, output_size):
        super(LR, self).__init__()  ## 这一行不是很懂
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        out = self.linear(x)
        return out

In [20]:
lr = LR (1,1)
print (list(lr.parameters()))

[Parameter containing:
tensor([[0.5916]], requires_grad=True), Parameter containing:
tensor([-0.1449], requires_grad=True)]


In [19]:
print (lr.linear)

Linear(in_features=1, out_features=1, bias=True)


# Linear Regression 1D; Traning 1 parameter

In [22]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
class plot_diagram ():

    # constructor 构造器
    def __init__ (self, X, Y, w, stop, go=False):
        start = w.data
        self.error = []
        srlf.parameter = []
        self.X = X.numpy()
        self.Y = Y.numpy()
        self.parameter_values = torch.arange(start, stop)
        self.Loss_function = [criterion(forward(X), Y)] for w.data in self.parameter_values]
        w.data = start

    # executor 执行器
    def __call__(self, Yhat, w, error, n):
        self.error.append(error)
        self.parameter.append(w.data)
        plt.subplot(212)
        plt.plot(self.X, Yhat.detach().numpy())
        plt.plot(self.X, self.Y,'ro')
        plt.xlabel("A")
        plt.ylim(-20, 20)
        plt.subplot(211)
        plt.title("Data Space (top) Estimated Line (bottom) Iteration " + str(n))
        plt.plot(self.parameter_values.numpy(), self.Loss_function)   
        plt.plot(self.parameter, self.error, 'ro')
        plt.xlabel("B")
        plt.figure()

    # Destructor 破坏器
    def __del__(self):
        plt.close('all')

In [23]:
import torch

In [26]:
X = torch.arange(-3,3,0.1).view(-1,1) ## the view function here is equal to reshape, make sure the 
print (X)

tensor([[-3.0000],
        [-2.9000],
        [-2.8000],
        [-2.7000],
        [-2.6000],
        [-2.5000],
        [-2.4000],
        [-2.3000],
        [-2.2000],
        [-2.1000],
        [-2.0000],
        [-1.9000],
        [-1.8000],
        [-1.7000],
        [-1.6000],
        [-1.5000],
        [-1.4000],
        [-1.3000],
        [-1.2000],
        [-1.1000],
        [-1.0000],
        [-0.9000],
        [-0.8000],
        [-0.7000],
        [-0.6000],
        [-0.5000],
        [-0.4000],
        [-0.3000],
        [-0.2000],
        [-0.1000],
        [ 0.0000],
        [ 0.1000],
        [ 0.2000],
        [ 0.3000],
        [ 0.4000],
        [ 0.5000],
        [ 0.6000],
        [ 0.7000],
        [ 0.8000],
        [ 0.9000],
        [ 1.0000],
        [ 1.1000],
        [ 1.2000],
        [ 1.3000],
        [ 1.4000],
        [ 1.5000],
        [ 1.6000],
        [ 1.7000],
        [ 1.8000],
        [ 1.9000],
        [ 2.0000],
        [ 2.1000],
        [ 2.