In [1]:
import numpy as np
from scipy import integrate
import matplotlib.pyplot as plt

%matplotlib qt

# straight line

In [2]:
points = 255
x = np.linspace(0.000001, 2*np.pi, points, endpoint=False).reshape(-1,1)
line1 = np.ones(len(x)) - (1-(1/(2*np.pi)))
line1 = line1.reshape(points,1)
line2 = line1.copy()
line2[0] = 0.05
line2[-1] = 0.05

y1 = np.sin(x)**2 / (np.pi)
y2 = np.cos(x)**2 / (np.pi)

def matrix(x):
    matrics = np.zeros([len(x), len(x)])
    for i in range(len(x)):
        for j in range(len(x)):
            matrics[i][j] = np.abs(np.sin(x[i] - x[j]))
    return matrics

matrix = matrix(x)



simpson matrix

In [3]:
simpson_matrix = np.zeros(len(x))
for i in range (len(x)):
    if i%2 == 0:
        simpson_matrix[i] = 2
    if i%2 != 0:
        simpson_matrix[i] = 4
simpson_matrix[0], simpson_matrix[-1] = 1, 1
simpson_matrix = simpson_matrix.reshape(1, -1)


In [4]:
def new_loss (yhat, rho, simpson_matrix, matrix, lambd):
    f1 = np.dot(yhat, yhat.T) * matrix
    dx = x[1] - x[0]
    first_term = (dx/3) * np.dot(simpson_matrix,yhat * np.log(rho * yhat))
    second_term = (rho/2) * (dx/3)**2 * np.dot(np.dot(simpson_matrix, f1), simpson_matrix.T)
    third_term = lambd * (((dx/3) *(np.dot(simpson_matrix,yhat))) - 1 ) **2
    loss = first_term + second_term + third_term
    return first_term, second_term, third_term, loss

In [5]:
new_loss(line1, 3, simpson_matrix, matrix, 200)

(array([[-0.73636558]]),
 array([[0.94741983]]),
 array([[0.00307599]]),
 array([[0.21413024]]))

In [239]:
new_loss(line2, 4, simpson_matrix, matrix, 200)

(array([[-0.45137475]]),
 array([[1.27138238]]),
 array([[0.00010633]]),
 array([[0.82011395]]))

In [240]:
new_loss(y1, 6, simpson_matrix, matrix, 200)

(array([[0.26073526]]),
 array([[1.59154843]]),
 array([[2.17113554e-15]]),
 array([[1.85228369]]))

In [243]:
new_loss(y2, 6, simpson_matrix, matrix, 200)

(array([[0.26008767]]),
 array([[1.58899989]]),
 array([[0.00020033]]),
 array([[1.84928788]]))

In [234]:
dx = x[1] - x[0]
(dx/3) *(np.dot(simpson_matrix,y1))


array([[0.5]])