In [56]:
import numpy as np
from scipy import integrate
import matplotlib.pyplot as plt

%matplotlib qt

In [2]:
points = 1000
x = np.linspace(0.000001, 2*np.pi, points, endpoint=False).reshape(points,1)
y1 = np.sin(x)**2
y2 = np.cos(x)**2

In [3]:
def matrix(x):
    matrics = np.zeros([len(x), len(x)])
    for i in range(len(x)):
        for j in range(len(x)):
            matrics[i][j] = np.abs(np.sin(x[i] - x[j]))
    return matrics

In [4]:
matrix = matrix(x)

In [82]:
def free_energy(yhat, x, matrix, rho, lambd):
    L = len(yhat)
    first_term = (2 * np.pi / (L)) * (np.dot(yhat.T, np.log(rho * yhat)))
    first_term = np.abs(integrate.trapz((yhat*np.log(rho*yhat)).T, x.T))
    second_term = (2 * np.pi ** 2 * rho / (L) ** 2) * np.dot(np.dot(yhat.T, matrix), yhat)
    third_term = lambd * integrate.trapz(integrate.simps(yhat.T, x.T) - 1)
    loss = first_term \
           + second_term \
           + third_term
    return first_term, second_term,third_term,loss

In [83]:
print ("this is the result of sin")
free_energy(y1,x,matrix,6,20)

this is the result of sin


(array([4.41539995]), array([[15.70787527]]), 0.0, array([[20.12327523]]))

In [84]:
print ("this is the result of cos")
free_energy(y2,x,matrix,6,20)

this is the result of cos


(array([4.40413952]), array([[15.70786727]]), 0.0, array([[20.11200679]]))

### 验证直线项

In [85]:
line1 = np.ones(len(x)) - (1-(1/(2*np.pi)))
line1 = line1.reshape(points,1)
line2 = line1.copy()
line2[0] = 0.05
line2[-1] = 0.05

integral of lines

In [86]:
integrate.trapz(line1.T, x.T)

array([0.99899984])

In [87]:
free_energy(line1, x, matrix, 2*np.pi, 20)

(array([2.21822525e-16]), array([[1.99999342]]), 0.0, array([[1.99999342]]))

In [88]:
free_energy(line2, x, matrix, 2*np.pi, 20)

(array([0.00036375]), array([[1.99450673]]), 0.0, array([[1.99487048]]))

画出交点
1. 第一项和积分的值有关，积分越接近1， 误差越小，可以先尝试，画出横轴是积分值， 纵轴是lost

In [60]:
vec1 = np.arange(2*np.pi, 7, 0.01)
integral1 = []
diff_points = []
for i in vec1:
    line1 = np.ones(len(x)) - (1-(1/(i)))
    line1 = line1.reshape(points,1)
    line2 = line1.copy()
    line2[0] = 0.05
    line2[-1] = 0.05
    integral1.append(integrate.trapz(line1.T, x.T))
    first1, _, _, _ = free_energy(line1, x, matrix, 4, 20)
    first2, _, _, _ = free_energy(line2, x, matrix, 4, 20)
    diff = first1 - first2
    diff_points.append(diff)

In [63]:
plt.plot(integral1, diff_points)
# plt.plot(x, line1)