In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## prediction

In [4]:
w = torch.tensor(2.0, requires_grad = True )
b = torch.tensor(-1.0, requires_grad = True )
print (w,b)

tensor(2., requires_grad=True) tensor(-1., requires_grad=True)


In [5]:
def forward(x):
    yhat = w*x +b
    return yhat

In [6]:
x = torch.tensor([1.0])
yhat = forward(x)
print (yhat)

tensor([1.], grad_fn=<AddBackward0>)


In [13]:
x = torch.tensor([[1.0],[2.0]])
print (x)
print (x.shape)

tensor([[1.],
        [2.]])
torch.Size([2, 1])


In [14]:
yhat = forward(x)
print (yhat)
print (yhat.shape)

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)
torch.Size([2, 1])


## class linear

In [15]:
from torch.nn import Linear

In [25]:
lr = Linear(in_features=1, out_features=2, bias=True)
print (list(lr.parameters()))

[Parameter containing:
tensor([[-0.0044],
        [ 0.6543]], requires_grad=True), Parameter containing:
tensor([0.6912, 0.5799], requires_grad=True)]


**in_features** – size of each input sample

**out_features** – size of each output sample

**bias** – If set to False, the layer will not learn an additive bias. Default: True

In [24]:
lr = Linear(in_features=4, out_features=1, bias=True)
print (list(lr.parameters()))

[Parameter containing:
tensor([[0.1426, 0.2676, 0.4319, 0.3374]], requires_grad=True), Parameter containing:
tensor([-0.3052], requires_grad=True)]
